<a href="https://colab.research.google.com/github/Sivasindhuja/Machine-Learning-Lab/blob/main/mllab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#verify machine learning environment

import pandas as pd
import numpy as np
import matplotlib as mp

print(pd.__version__)
print(np.__version__)
print(mp.__version__)


2.2.2
2.0.2
3.10.0


In [2]:
pip install scikit-learn


In [4]:
#human learning vs machine learning

def even_odd(num):
  if(num%2==0):
    print("even")

  else:
    print("odd")

even_odd(10)
even_odd(11)

print("hello world")

#machine learning
import numpy as np
from sklearn.tree import DecisionTreeClassifier


#dataset
X_train=np.arange(1000).reshape(-1,1)
y_train=X_train % 2

model=DecisionTreeClassifier()
model.fit(X_train,y_train)


test_numbers=np.array([12,15]).reshape(-1,1)


predictions=model.predict(test_numbers)

print(predictions)


even
odd
hello world
[0 1]


In [21]:
#load a dataset,number of records,attributes,datatypes,statistical information

from sklearn.datasets import load_iris
import pandas as pd

iris=load_iris()

iris_data_frame=pd.DataFrame(iris.data,columns=iris.feature_names)

#first five records
print("first five records")
print(iris_data_frame.head)


#shape of the dataframe
print("shape of the dataframe")
print(iris_data_frame.shape)


#number of columns
print("number of columns")
print(iris_data_frame.shape[1])


#number of records
print("number of records")
print(iris_data_frame.shape[0])


#datatype
print("datatypes")
print(iris_data_frame.dtypes)


#statistical information
print("mean is ",iris_data_frame.mean())
print("median is",iris_data_frame.median())

print("minimum value is ",iris_data_frame.min())
print("maximum value is",iris_data_frame.max())


first five records
<bound method NDFrame.head of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 

In [28]:
#data quality issues missing values,duplicates

from sklearn.datasets import load_iris
import pandas as pd

iris=load_iris()

iris_data_frame=pd.DataFrame(iris.data,columns=iris.feature_names)

#find missing values

print("missing values",iris_data_frame.isnull().sum())

#find duplicates

print("duplicated",iris_data_frame.duplicated().sum())





missing values sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64
duplicated 1


In [33]:
#handle missing values

from sklearn.datasets import fetch_openml

titanic=fetch_openml('titanic',version=1,as_frame=True)

titanic_data_frame=pd.DataFrame(titanic.data,columns=titanic.feature_names)

missing_values=titanic_data_frame.isnull().sum()
print(missing_values)

#handle them

cleaned_data_frame=titanic_data_frame.drop(columns=['body' , 'cabin' , 'home.dest' , 'boat'])

cleaned_data_frame['age']=cleaned_data_frame['age'].fillna(cleaned_data_frame['age'].median())
cleaned_data_frame['fare']=cleaned_data_frame['fare'].fillna(cleaned_data_frame['fare'].median())

cleaned_data_frame['embarked']=cleaned_data_frame['embarked'].fillna(cleaned_data_frame['embarked'].mode()[0])

#print cleaned dataframe

missing_values_after_clean=cleaned_data_frame.isnull().sum()

print("after clean",missing_values_after_clean)

pclass          0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64
after clean pclass      0
name        0
sex         0
age         0
sibsp       0
parch       0
ticket      0
fare        0
embarked    0
dtype: int64


In [35]:
#categorical to numeric data

#one-hot encoding
#label encoding
from sklearn.datasets import fetch_openml

titanic=fetch_openml('titanic',version=1,as_frame=True)

titanic_data_frame=pd.DataFrame(titanic.data,columns=titanic.feature_names)

#introduce categorical data to the titanic dataset

titanic_encoded=pd.get_dummies(titanic_data_frame,columns=['sex','embarked'])
print(titanic_encoded.head())


#label encoding

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
titanic_data_frame['sex']=le.fit_transform(titanic_data_frame['sex'])
titanic_data_frame['embarked']=le.fit_transform(titanic_data_frame['embarked'])

print(titanic_data_frame.head())


   pclass                                             name      age  sibsp  \
0       1                    Allen, Miss. Elisabeth Walton  29.0000      0   
1       1                   Allison, Master. Hudson Trevor   0.9167      1   
2       1                     Allison, Miss. Helen Loraine   2.0000      1   
3       1             Allison, Mr. Hudson Joshua Creighton  30.0000      1   
4       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000      1   

   parch  ticket      fare    cabin boat   body  \
0      0   24160  211.3375       B5    2    NaN   
1      2  113781  151.5500  C22 C26   11    NaN   
2      2  113781  151.5500  C22 C26  NaN    NaN   
3      2  113781  151.5500  C22 C26  NaN  135.0   
4      2  113781  151.5500  C22 C26  NaN    NaN   

                         home.dest  sex_female  sex_male  embarked_C  \
0                     St Louis, MO        True     False       False   
1  Montreal, PQ / Chesterville, ON       False      True       False   
2  Montr

In [41]:
#UCImlrepo using URL

import pandas as pd

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"


#define column names

column_names=['sepal_length','sepal_width','petal_length','petal_width','class']

df=pd.read_csv(url , names=column_names)

print(df.head())

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [42]:
#save as CSV

#UCImlrepo using URL

import pandas as pd

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"


#define column names

column_names=['sepal_length','sepal_width','petal_length','petal_width','class']

df=pd.read_csv(url , names=column_names)

print(df.head())

file_name='iris_dataset.csv'

df.to_csv(file_name,index=False)

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [44]:
pip install ucimlrepo


In [45]:
#using python

from ucimlrepo import fetch_ucirepo

iris=fetch_ucirepo(id=53)

X=iris.data.features
y=iris.data.targets

print(X.head())

   sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In [48]:
#split into training and testing data
from sklearn.datasets import load_iris
iris=load_iris()

X=iris.data
y=iris.target

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)



(120, 4)
(30, 4)
(120,)
(30,)


In [54]:
#print sample records
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()

X=iris.data
y=iris.target

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

X_train_df=pd.DataFrame(X_train,columns=iris.feature_names)
print(X_train_df.head())

X_test_df=pd.DataFrame(X_test,columns=iris.feature_names)
print(X_test_df.head())

y_test_df=pd.DataFrame(y_test,columns=['target'])
print(y_test_df.head())


y_train_df=pd.DataFrame(y_train,columns=['target'])
print(y_train_df.head())


(120, 4)
(30, 4)
(120,)
(30,)
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                4.6               3.6                1.0               0.2
1                5.7               4.4                1.5               0.4
2                6.7               3.1                4.4               1.4
3                4.8               3.4                1.6               0.2
4                4.4               3.2                1.3               0.2
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                6.1               2.8                4.7               1.2
1                5.7               3.8                1.7               0.3
2                7.7               2.6                6.9               2.3
3                6.0               2.9                4.5               1.5
4                6.8               2.8                4.8               1.4
   target
0       1
1       0
2       2
3       1
4       

In [57]:
#kmeans
#1.load the dataset
#2.apply k-means with 3 clusters
#3.print the number of cluster centers and number of samples in each cluster

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans

iris=load_iris()
X=pd.DataFrame(iris,columns=iris.feature_names)

kmeans=KMeans(n_clusters=3)

X['cluster']=kmeans.fit(iris.data)

print(kmeans.cluster_centers_)
print(X['cluster'].value_counts())


[[5.9016129  2.7483871  4.39354839 1.43387097]
 [5.006      3.428      1.462      0.246     ]
 [6.85       3.07368421 5.74210526 2.07105263]]
Series([], Name: count, dtype: int64)


In [68]:
#using iris dataset,supervised learning model,performance evaluation using accuracy,confusion matrix,precision,recall and f1 score

from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score,classification_report
iris=load_iris()

X=iris.data
y=iris.target
target_names=iris.target_names

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

model=LogisticRegression()
model.fit(X_train,y_train)

y_predict=model.predict(X_test)
print(y_predict)

print(accuracy_score)

classification_report=classification_report(y_test,y_predict,target_names=target_names)

print(classification_report)





[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
<function accuracy_score at 0x7df2fce39e40>
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [81]:
#K-Nearest_Neighbours algorithm for brest cancer dataset
#model performance by varying the values of k

from sklearn.datasets import load_breast_cancer
bc=load_breast_cancer()

from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=5)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(bc.data,bc.target,test_size=0.2,random_state=42)

model.fit(X_train,y_train)

y_predict=model.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)


0.956140350877193


In [86]:
#naive bayes
from sklearn.datasets import load_iris
iris=load_iris()

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

from sklearn.model_selection import train_test_split
X=iris.data
y=iris.target

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model.fit(X_train,y_train)
y_predict=model.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)




1.0


In [88]:
#Desicion tree
from sklearn.datasets import load_iris
iris=load_iris()

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

from sklearn.model_selection import train_test_split
X=iris.data
y=iris.target

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model.fit(X_train,y_train)
y_predict=model.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)


1.0


In [89]:
#random forest
from sklearn.datasets import load_iris
iris=load_iris()

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)

from sklearn.model_selection import train_test_split
X=iris.data
y=iris.target

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model.fit(X_train,y_train)
y_predict=model.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)


1.0
